### ISSUE TITLE
Tests to prove successful build & CI

### ISSUE THREAD

**Issue by danielpclark** [malept/thermite#1]
There doesn't seem to be any tests that proves this works or that it won't break.  I would like a test for Thermite that shows a successful Rust library is built when a gem is bundle installed.  Also verify that code such as this:

```ruby
toplevel_dir = File.dirname(File.dirname(__FILE__))
config = Thermite::Config.new(cargo_project_path: toplevel_dir,
                                    ruby_project_path: toplevel_dir)
config.ruby_extension_path
```

finds the built library after a bundle install.

**Comment by malept** [comment]
Admittedly, a lot of the (integration) tests I've written for thermite are actually in [`rusty_blank`](https://github.com/malept/rusty_blank). I need to think of a good way to deal with that dependency without bundling the example code in this repository (or adding a submodule).

I also need to figure out what the best way to write unit tests are (aside from `Thermite::Config`, that seems pretty straightforward) since I've broken it up into modules.

**Comment by malept** [comment]
Aha, you can [trigger Travis CI builds from an API](https://docs.travis-ci.com/user/triggering-builds). I will try to implement that soon.

Meanwhile in the `rusty_blank` repository, I'm trying to "prove" that you can install and run a gem from a binary package. That is proving more difficult than I thought it would be, due to Travis's Ruby/RVM configuration.

**Comment by danielpclark** [comment]
Perhaps you could do something like `bundle install --path vendor/bundle` to a temporary directory with a development dependency of your `rusty_blank` example, test it, the clean the temporary directory.

**Comment by malept** [comment]
I added the trigger for both AppVeyor CI and Travis CI in https://github.com/malept/thermite/commit/047cd0fd91ce86fafd123e9c54a94d68468be527. Still working on testing `gem install`, I want to be able to do it without using `bundler`.

**Comment by danielpclark** [comment]
So I stumbled across this site [https://rubybench.org/](https://rubybench.org/) and they have the Bundler temporary directory build in it: https://github.com/ruby-bench/ruby-bench-suite/blob/master/bundler/benchmarks/bm_bundle_exec_gem.rb .  They're using it for benchmarks, but it would be perfect for testing lib extension building.

**Comment by malept** [comment]
@danielpclark:

I figured out (almost) all of the `gem install` related problems (and by almost, I mean `rusty_blank` CI *was* working on AppVeyor for a time, but now it's not and I'm not sure why).

Take a look at all of the test-related commits since https://github.com/malept/thermite/commit/1416022451b84801c4a25db83b4232f40754b1ec and see if they are to your satisfaction. I think I have 100% branch coverage.

I should probably add OSX/Windows CI in this particular repository before I close this issue.

**Comment by malept** [comment]
I've added OSX/Windows CI and there's a new 0.5.0 release with all of these changes.
